theme: jekyll-theme-cayman
name: Jeremy Booth
title: CDEFO
description: The Premiere Emotional UbiComp Emulator
email: booth212092@gmail.com
github_username:  TeleBooth

# Build settings
include: ['_pages']
kramdown:
    input: GFM