theme: jekyll-theme-cayman
name: Jeremy Booth
title: CDEFO
description: The Premiere Emotional UbiComp Emulator
email: booth212092@gmail.com
github_username:  TeleBooth

# Build settings
baseurl: /CDEFO
include: ['_plugins', '_pages', '_assets']
category-list: [build-log, tutorial, documentation]

safe: false

kramdown:
    input: GFM