from setuptools import setup

setup(
    name='CDEFO_python',
    version='',
    packages=['CDEFO_python.venv.Lib.distutils', 'CDEFO_python.venv.Lib.encodings', 'CDEFO_python.venv.Lib.importlib',
              'CDEFO_python.venv.Lib.collections', 'CDEFO_python.venv.Lib.site-packages.bs4',
              'CDEFO_python.venv.Lib.site-packages.bs4.tests', 'CDEFO_python.venv.Lib.site-packages.bs4.builder',
              'CDEFO_python.venv.Lib.site-packages.pip', 'CDEFO_python.venv.Lib.site-packages.pip.req',
              'CDEFO_python.venv.Lib.site-packages.pip.vcs', 'CDEFO_python.venv.Lib.site-packages.pip.utils',
              'CDEFO_python.venv.Lib.site-packages.pip.compat', 'CDEFO_python.venv.Lib.site-packages.pip.models',
              'CDEFO_python.venv.Lib.site-packages.pip._vendor',
              'CDEFO_python.venv.Lib.site-packages.pip._vendor.distlib',
              'CDEFO_python.venv.Lib.site-packages.pip._vendor.distlib._backport',
              'CDEFO_python.venv.Lib.site-packages.pip._vendor.colorama',
              'CDEFO_python.venv.Lib.site-packages.pip._vendor.html5lib',
              'CDEFO_python.venv.Lib.site-packages.pip._vendor.html5lib._trie',
              'CDEFO_python.venv.Lib.site-packages.pip._vendor.html5lib.filters',
              'CDEFO_python.venv.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'CDEFO_python.venv.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'CDEFO_python.venv.Lib.site-packages.pip._vendor.html5lib.treebuilders',
              'CDEFO_python.venv.Lib.site-packages.pip._vendor.lockfile',
              'CDEFO_python.venv.Lib.site-packages.pip._vendor.progress',
              'CDEFO_python.venv.Lib.site-packages.pip._vendor.requests',
              'CDEFO_python.venv.Lib.site-packages.pip._vendor.requests.packages',
              'CDEFO_python.venv.Lib.site-packages.pip._vendor.requests.packages.chardet',
              'CDEFO_python.venv.Lib.site-packages.pip._vendor.requests.packages.urllib3',
              'CDEFO_python.venv.Lib.site-packages.pip._vendor.requests.packages.urllib3.util',
              'CDEFO_python.venv.Lib.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'CDEFO_python.venv.Lib.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'CDEFO_python.venv.Lib.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'CDEFO_python.venv.Lib.site-packages.pip._vendor.packaging',
              'CDEFO_python.venv.Lib.site-packages.pip._vendor.cachecontrol',
              'CDEFO_python.venv.Lib.site-packages.pip._vendor.cachecontrol.caches',
              'CDEFO_python.venv.Lib.site-packages.pip._vendor.webencodings',
              'CDEFO_python.venv.Lib.site-packages.pip._vendor.pkg_resources',
              'CDEFO_python.venv.Lib.site-packages.pip.commands', 'CDEFO_python.venv.Lib.site-packages.pip.operations',
              'CDEFO_python.venv.Lib.site-packages.idna', 'CDEFO_python.venv.Lib.site-packages.wheel',
              'CDEFO_python.venv.Lib.site-packages.wheel.tool', 'CDEFO_python.venv.Lib.site-packages.wheel.signatures',
              'CDEFO_python.venv.Lib.site-packages.serial', 'CDEFO_python.venv.Lib.site-packages.serial.tools',
              'CDEFO_python.venv.Lib.site-packages.serial.threaded',
              'CDEFO_python.venv.Lib.site-packages.serial.urlhandler', 'CDEFO_python.venv.Lib.site-packages.certifi',
              'CDEFO_python.venv.Lib.site-packages.chardet', 'CDEFO_python.venv.Lib.site-packages.chardet.cli',
              'CDEFO_python.venv.Lib.site-packages.spotipy', 'CDEFO_python.venv.Lib.site-packages.urllib3',
              'CDEFO_python.venv.Lib.site-packages.urllib3.util', 'CDEFO_python.venv.Lib.site-packages.urllib3.contrib',
              'CDEFO_python.venv.Lib.site-packages.urllib3.contrib._securetransport',
              'CDEFO_python.venv.Lib.site-packages.urllib3.packages',
              'CDEFO_python.venv.Lib.site-packages.urllib3.packages.backports',
              'CDEFO_python.venv.Lib.site-packages.urllib3.packages.ssl_match_hostname',
              'CDEFO_python.venv.Lib.site-packages.requests', 'CDEFO_python.venv.Lib.site-packages.setuptools',
              'CDEFO_python.venv.Lib.site-packages.setuptools.extern',
              'CDEFO_python.venv.Lib.site-packages.setuptools.command',
              'CDEFO_python.venv.Lib.site-packages.googlesearch', 'CDEFO_python.venv.Lib.site-packages.pkg_resources',
              'CDEFO_python.venv.Lib.site-packages.pkg_resources.extern',
              'CDEFO_python.venv.Lib.site-packages.pkg_resources._vendor',
              'CDEFO_python.venv.Lib.site-packages.pkg_resources._vendor.packaging'],
    url='',
    license='',
    author='Jeremy',
    author_email='',
    description=''
)
